### ISSUE TITLE
Build Failure deploying to Cloudhub IllegalStateException

### ISSUE THREAD

**Issue by GoBenGoh** [mulesoft-catalyst/metrics-toolkit#165] opened 2021-12-08 22:32 UTC
I tried to deploy the toolkit (mule-4.4.0 branch) to Cloudhub but I'm getting an IllegalStateException: "Cannot start embedded container". The toolkit appears to work fine on my localhost. Here are the event details from the error log. 
![image](https://user-images.githubusercontent.com/76719511/145300606-684bae1d-2fbd-4036-92cf-e660b95d6484.png)

**Comment by GoBenGoh** [comment] 2021-12-09 02:40
![image](https://user-images.githubusercontent.com/76719511/145324536-c1097b64-1df8-472c-b098-df1c52e44422.png)
Here is the final error message

**Comment by richardmckinley** [comment] 2021-12-09 10:33
Hi @GoBenGoh 
It looks like this is an error executing the MUnit tests before packaging the deployable. If you execute `mvn clean test` on the project you should get an output similar to this:
![image](https://user-images.githubusercontent.com/58299919/145379022-649ec569-bc8b-4bf5-8740-79ee99a31f86.png)
If not, there is likely something wrong with your Maven setup, which I cannot advise on. 
For reference, how are you deploying to CloudHub? For example, I have just tested deploying by exporting the .jar from Studio and uploading to CloudHub without issue. This will not resolve your MUnit/Maven issue but may be a temporary workaround. 
Richard

**Comment by cajhughes** [comment] 2021-12-09 16:03
Not sure if it's directly related, but just noticed that I needed to change the following:

- https://github.com/mulesoft-catalyst/metrics-toolkit/blob/e62ec39dcb8ee9c015c29a2156a01fe88381d4c0/src/main/mule/aggregators/aggregator-platform-benefits-metrics.xml#L12
- https://github.com/mulesoft-catalyst/metrics-toolkit/blob/e62ec39dcb8ee9c015c29a2156a01fe88381d4c0/src/main/mule/aggregators/aggregator-platform-metrics.xml#L18

Change `targetValue="payload.access_token"` references to `targetValue="#[payload.access_token]"`

**Comment by GoBenGoh** [comment] 2021-12-09 21:31
I'm just exporting it straight to Cloudhub from Anypoint Studio. When I try to export the .jar and upload it, it says that the file size is too big. Also I can run the MUnit tests fine from Anypoint Studio. The error messages I get are purely from trying to upload it to Cloudhub.

**Comment by GoBenGoh** [comment] 2021-12-12 22:03
I'm deploying to Cloudhub via Anypoint Studio. I think it's an error with my MUnit or Maven like you said. I cannot run the app if -DskipMunitTests is not present in the Maven command for building.

Here is a screenshot of the errors:
![image](https://user-images.githubusercontent.com/76719511/145731329-152893d7-9bcb-45ab-b732-70f2c9001a33.png)

**Comment by GoBenGoh** [comment] 2021-12-13 01:53
I've also found that MUnit works fine on my other projects. I'm guessing the pom file you used is exactly the same as the one from the 4.4.0 branch?

**Comment by richardmckinley** [comment] 2021-12-13 12:25
Yes I've just cleaned my local Maven repo, and run from `feature/mule-4.4.0` to double check and it's working as expected. 

I think you should check out this [article](https://help.mulesoft.com/s/article/Unable-to-find-the-dependency-com-mulesoft-mule-distributions-mule-runtime-impl-bom-pom-when-building-through-maven) as I suspect this is the cause. 

As I can't reproduce I'm going to close this as not being an issue related to the toolkit. I'm afraid I cannot provide any support on Mule runtime, Maven etc. issues. If you need help with these you can reach out to your Customer Success Manager to direct you appropriately. 

If you come across issues that you think are directly related to the toolkit then please do open another issue. 

Thanks, 
Richard

**Closed by richardmckinley** 2021-12-13 12:25 UTC

**Comment by GoBenGoh** [comment] 2021-12-13 22:41
I found a few people with a similar issue to me online. Is one of the dependencies only accessible from a mule enterprise repository rather than a public mule repository? Because it seems like the most common answer to my issue is setting up my maven settings.xml file to access the enterprise repository which requires credentials from Mulesoft Support.

**Comment by richardmckinley** [comment] 2021-12-14 09:47
> I found a few people with a similar issue to me online. Is one of the dependencies only accessible from a mule enterprise repository rather than a public mule repository? Because it seems like the most common answer to my issue is setting up my maven settings.xml file to access the enterprise repository which requires credentials from Mulesoft Support.

Yes - that's what is described in the article linked above

**Comment by GoBenGoh** [comment] 2021-12-14 23:00
Sorry I don't know how I missed that. That was really dumb on my part.
